services:
  pdf_parser:
    build:
      context: .
      dockerfile: Dockerfile.pdf_parser
    ports:
      - "8080:8080"
    volumes:
      - ./logs/mlruns:/app/logs/mlruns
    networks:
      - app-network

  timeline:
    build:
      context: .
      dockerfile: Dockerfile.timeline
    ports:
      - "8082:8082"
    volumes:
      - ./logs/mlruns:/app/logs/mlruns
    networks:
      - app-network

networks:
  app-network:
    driver: bridge